pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'python3 /Users/yanchenghao/PycharmProjects/PycharmProjects/pythonProject/robot_learn/hello.py'

            }
        }
    }
}